### ISSUE TITLE
How to connect to Telenor Denmark?

### ISSUE THREAD

**Issue by m-tach** [TelenorStartIoT/arduino-dev-kit-coap#1]
Hello,

We are MSc students at DTU in Copenhagen and for a special course we need to set up a [SODAQ SARA AFF N211 ](https://shop.sodaq.com/sodaq-sara-aff-n211.html) board to connect using a Telenor DK SIM card.

Your repository has been extremely helpful, however we are stuck in "searching for network mode". We figured that it is because we have not configured the correct APN/COPS.
We tried to reach out to Telenor customer service, but they had no idea what TelenorIoT was.

Can you help us get in touch with the people who know the correct configuration required? We need the Telenor DK APN, Telenor DK IP address and Telenor DK "shortname" as you call it (basically the MCC-MNC numbers).

Thank you for taking the time to read this,
Mariya

**Comment by Pwntus** [comment]
Hi @m-tach !

Please send us an email at startiot@telenor.com and we'll get in touch with you!

**Comment by Pwntus** [comment]
To summarize:

At the moment we only provide IoT Gateway in Telenor Norway. If you want to utilize IoT Gateway (and CoAP) you must have a SIM-card from Telenor Norway and connect to the **telenor.iotgw** APN.

By connecting to the cellular network (which gives public internet access) in any other way you must use MQTT with X.509 client certificates to establish a secured connection. The following tutorial describes how to provision a device and aquire these certificates in [Telenor Managed IoT Cloud (MIC)](https://demonorway.mic.telenorconnexion.com/), in addition to how to program a Pycom FiPy and setup an MQTT client: https://startiot.telenor.com/tutorials/fipy-dev-kit-mqtt/

Parameters for CoAP and MQTT are listed here: https://telenorstartiot.github.io/

I will close this issue for now.
