### ISSUE TITLE
coap.start() need NB-connection to get a socket

### ISSUE THREAD

**Issue by halftanolger** [TelenorStartIoT/arduino-dev-kit-coap#2]
Inserting this code
 
  // Check if connected and if not, reconnect
  if (nbAccess.status() != NB_READY || gprsAccess.status() != GPRS_READY) {
    connectNB();
  }

before calling coap.start() in main.ino , did get my Arduino MKR NB connected to Telenor :-)

**Comment by Pwntus** [comment]
Fantastic @halftanolger !
This also makes totally sense. I will implement the changes asap into the code.

**Comment by Pwntus** [comment]
Closing in favor of #3
