### ISSUE TITLE
Packet.paylodlen is not set correctly.

### ISSUE THREAD

**Issue by johanhef** [TelenorStartIoT/arduino-dev-kit-coap#7]
coap.h, class CoapPacket payloadlen is type uint8_t.
Should be uint32_t
Packet.paylodlen is not set correctly when using coap.send because payloadlen is uint32_t.

**Comment by steffennilsen** [comment]
This codes comes from https://github.com/hirotakaster/CoAP-simple-library/blob/master/coap-simple.h. I see the code has been updated to use `size_t` and I am going to look into updating our library.

**Comment by steffennilsen** [comment]
fixed in #9
